#!/usr/bin/env ruby

require_relative 'lib/month'
require_relative 'lib/year'

if ARGV.length == 1
  year = ARGV[0].to_i
  year = Year.new(year)
  puts year.to_s

elsif ARGV.length >= 3
  puts "usage: cal [month] year"

else
  month = ARGV[0].to_i
  year = ARGV[1].to_i
  month = Month.new(month, year)
  puts month.to_s
end
